export interface DrugCatalogItem {
  id: string
  name: string
  genericName: string
  category: string
  commonDosages: string[]
  forms: ('Tablet' | 'Capsule' | 'Syrup' | 'Injection' | 'Inhaler' | 'Drops' | 'Ointment')[]
  defaultForm: 'Tablet' | 'Capsule' | 'Syrup' | 'Injection' | 'Inhaler' | 'Drops' | 'Ointment'
  defaultFrequency: string
  defaultDuration: string
  standardInstructions: string
  allergyClass?: string // e.g. "Penicillin", "NSAID", "Sulfa"
}

export const DRUG_CATALOG: DrugCatalogItem[] = [
  {
    id: 'drug-1',
    name: 'Amoxicillin',
    genericName: 'Amoxicillin Trihydrate',
    category: 'Antibiotic (Penicillin class)',
    commonDosages: ['250mg', '500mg', '875mg'],
    forms: ['Capsule', 'Tablet', 'Syrup'],
    defaultForm: 'Capsule',
    defaultFrequency: '1-1-1 (Every 8 hours)',
    defaultDuration: '7 Days',
    standardInstructions: 'Take with a full glass of water. Complete full course even if feeling better.',
    allergyClass: 'Penicillin',
  },
  {
    id: 'drug-2',
    name: 'Augmentin',
    genericName: 'Amoxicillin + Clavulanate Potassium',
    category: 'Antibiotic (Penicillin class)',
    commonDosages: ['625mg', '1000mg ER'],
    forms: ['Tablet', 'Syrup'],
    defaultForm: 'Tablet',
    defaultFrequency: '1-0-1 (Twice daily with meals)',
    defaultDuration: '7 Days',
    standardInstructions: 'Take at the start of a meal to enhance absorption and reduce GI discomfort.',
    allergyClass: 'Penicillin',
  },
  {
    id: 'drug-3',
    name: 'Lisinopril',
    genericName: 'Lisinopril (Zestril)',
    category: 'Antihypertensive (ACE Inhibitor)',
    commonDosages: ['5mg', '10mg', '20mg', '40mg'],
    forms: ['Tablet'],
    defaultForm: 'Tablet',
    defaultFrequency: '1-0-0 (Morning with water)',
    defaultDuration: '90 Days',
    standardInstructions: 'Take once daily in morning. Check blood pressure regularly.',
  },
  {
    id: 'drug-4',
    name: 'Metformin HCl',
    genericName: 'Metformin Extended Release (Glucophage XR)',
    category: 'Antidiabetic (Biguanide)',
    commonDosages: ['500mg', '850mg', '1000mg'],
    forms: ['Tablet'],
    defaultForm: 'Tablet',
    defaultFrequency: '1-0-1 (With dinner / meals)',
    defaultDuration: '90 Days',
    standardInstructions: 'Take with evening meal to prevent stomach upset. Do not crush ER tablets.',
  },
  {
    id: 'drug-5',
    name: 'Atorvastatin',
    genericName: 'Atorvastatin Calcium (Lipitor)',
    category: 'Lipid Lowering (Statin)',
    commonDosages: ['10mg', '20mg', '40mg', '80mg'],
    forms: ['Tablet'],
    defaultForm: 'Tablet',
    defaultFrequency: '0-0-1 (Bedtime)',
    defaultDuration: '90 Days',
    standardInstructions: 'Take once daily at bedtime. Avoid excessive grapefruit consumption.',
  },
  {
    id: 'drug-6',
    name: 'Azithromycin',
    genericName: 'Azithromycin (Zithromax Z-Pak)',
    category: 'Antibiotic (Macrolide)',
    commonDosages: ['250mg', '500mg'],
    forms: ['Tablet', 'Syrup'],
    defaultForm: 'Tablet',
    defaultFrequency: '1-0-0 (Once daily)',
    defaultDuration: '5 Days',
    standardInstructions: 'Take 500mg on Day 1, then 250mg daily for Days 2-5.',
  },
  {
    id: 'drug-7',
    name: 'Albuterol Sulfate',
    genericName: 'Albuterol Inhalation Aerosol (ProAir / Ventolin)',
    category: 'Bronchodilator (Beta-2 Agonist)',
    commonDosages: ['90mcg / puff'],
    forms: ['Inhaler'],
    defaultForm: 'Inhaler',
    defaultFrequency: '1-2 puffs every 4-6 hours as needed',
    defaultDuration: '30 Days',
    standardInstructions: 'Inhale 2 puffs for acute shortness of breath. Rinse mouth after use.',
  },
  {
    id: 'drug-8',
    name: 'Omeprazole',
    genericName: 'Omeprazole Delayed-Release (Prilosec)',
    category: 'Proton Pump Inhibitor (PPI)',
    commonDosages: ['20mg', '40mg'],
    forms: ['Capsule'],
    defaultForm: 'Capsule',
    defaultFrequency: '1-0-0 (30 mins before breakfast)',
    defaultDuration: '30 Days',
    standardInstructions: 'Take in morning 30 minutes before first meal with a full glass of water.',
  },
  {
    id: 'drug-9',
    name: 'Aspirin (Low Dose)',
    genericName: 'Acetylsalicylic Acid (Bayer / Ecotrin)',
    category: 'Antiplatelet / NSAID',
    commonDosages: ['81mg', '325mg'],
    forms: ['Tablet'],
    defaultForm: 'Tablet',
    defaultFrequency: '1-0-0 (Morning with food)',
    defaultDuration: '90 Days',
    standardInstructions: 'Cardioprotective low-dose daily regimen. Take with food.',
    allergyClass: 'Aspirin (NSAIDs)',
  },
  {
    id: 'drug-10',
    name: 'Levothyroxine',
    genericName: 'Levothyroxine Sodium (Synthroid)',
    category: 'Thyroid Hormone Replacement',
    commonDosages: ['25mcg', '50mcg', '75mcg', '100mcg', '125mcg'],
    forms: ['Tablet'],
    defaultForm: 'Tablet',
    defaultFrequency: '1-0-0 (Empty stomach, 60 mins before eating)',
    defaultDuration: '90 Days',
    standardInstructions: 'Take first thing in morning with plain water only. Wait 60 mins before breakfast.',
  },
  {
    id: 'drug-11',
    name: 'Ibuprofen',
    genericName: 'Ibuprofen (Advil / Motrin)',
    category: 'NSAID / Analgesic',
    commonDosages: ['200mg', '400mg', '600mg', '800mg'],
    forms: ['Tablet', 'Syrup'],
    defaultForm: 'Tablet',
    defaultFrequency: '1-0-1 (After food as needed)',
    defaultDuration: '5 Days',
    standardInstructions: 'Always take with food or milk to prevent gastric irritation.',
    allergyClass: 'Aspirin (NSAIDs)',
  },
  {
    id: 'drug-12',
    name: 'Ciprofloxacin',
    genericName: 'Ciprofloxacin HCl (Cipro)',
    category: 'Antibiotic (Fluoroquinolone)',
    commonDosages: ['250mg', '500mg'],
    forms: ['Tablet', 'Drops'],
    defaultForm: 'Tablet',
    defaultFrequency: '1-0-1 (Every 12 hours)',
    defaultDuration: '7 Days',
    standardInstructions: 'Drink plenty of fluids. Avoid calcium/antacids 2 hours before or after.',
  },
  {
    id: 'drug-13',
    name: 'Celecoxib',
    genericName: 'Celecoxib (Celebrex)',
    category: 'COX-2 Selective NSAID',
    commonDosages: ['100mg', '200mg'],
    forms: ['Capsule'],
    defaultForm: 'Capsule',
    defaultFrequency: '1-0-1 (With food)',
    defaultDuration: '30 Days',
    standardInstructions: 'Take with food for joint pain and inflammation.',
    allergyClass: 'Sulfa Drugs (Sulfamethoxazole)',
  },
  {
    id: 'drug-14',
    name: 'Bactrim DS',
    genericName: 'Sulfamethoxazole + Trimethoprim (Bactrim)',
    category: 'Antibiotic (Sulfonamide)',
    commonDosages: ['800mg/160mg'],
    forms: ['Tablet'],
    defaultForm: 'Tablet',
    defaultFrequency: '1-0-1 (Every 12 hours)',
    defaultDuration: '10 Days',
    standardInstructions: 'Drink at least 8 glasses of water daily to prevent crystal formation.',
    allergyClass: 'Sulfa Drugs (Sulfamethoxazole)',
  },
]
